### ISSUE TITLE
Works perfectly with TypeScript

### ISSUE THREAD

**Issue by ilDon** [pshihn/workly#11]
I tried to make it as clear as possible in the title that this is not exactly an "issue" :-) 

I've been using workly in a TS project and it works like a charm. 

I thought I'd share here my experience, in case it helps. I think it might be useful also to add some of the following instructions to the README.

Since deferring to workly a pure TS class did not work (as expected), my approach was to build the classes I needed as a UMD with WebPack, and then the process is very simple. I'll explain it with some sample code.

Let's take the `Example` class in `./src/example.class.ts`:

    import { SomeThirdParyLibFromNpm } from 'someThirdParyLibFromNpm';
    import * as otherNpmLibWithoutTSSupport from 'otherNomLibWithoutTSSupport';
    import * as workly from 'workly';
    
    export class Example {
        constructor(
           private myState: AReduxState // example to clarify that we cannot rely on any kind of import, see later
        ) { }

       public someExpensiveTask(): any {
          const whatever = SomeThirdParyLibFromNpm.heavyCpu();
          const whatever += otherNpmLibWithoutTSSupport.otherExpensiveStuff();
          return whatever;
       }
    }
    
    workly.expose(Example);

The only thing that we must be aware of, is that this class cannot depend on global/scoped objects of the current project, like any process delegated to a WebWorker. So we cannot import a global `const` defined/modified at runtime, or rely on libraries like `Redux`. In such cases I would suggest to pass the values to the constructor like in the above example.

Then we build the UMD with WebPack. Here's my config for `webpack.worker.config.js`:

    const path = require('path');
    
    module.exports = {
      entry: {
        example: './src/example.class.ts'
      },
      resolve: {
        extensions: ['.ts']
      },
      target: 'webworker',
      node: {
        __dirname: true
      },
      output: {
        path: path.join(__dirname, 'src/assets/js'),
        filename: '[name].umd.min.js',
        library: 'Example',
        libraryTarget: 'umd'
      },
      module: {
        rules: [{
          test: /\.ts$/,
          loader: 'ts-loader'
        }]
      },
      mode: "production"
    }

Then run in the console:

    webpack --config webpack.worker.config.js --progress --colors

Then whenever we want to execute the `Example` class in a separate thread, thanks to workly we simply need to write in our TS code:

    import * as workly from 'workly';

    ....

    const WExample = workly.proxy('/assets/js/example.umd.min.js');
    const objWorker = await new WExample(this.myState);
    this.whatEver = await objWorker.someExpensiveTask();

In this way we get the double advantage of multi-threading our app, and also some chunks of our code can be downloaded only when needed :-).

PS Thanks for this awesome library!

**Comment by pshihn** [comment]
Glad you love it. Sorry, this package is one of my ignored children. Catching up on issues after a year!
