### ISSUE TITLE
Feature request: UMD export (again)

### ISSUE THREAD

**Issue by Finesse** [pshihn/workly#13]
Hi! The problem described in #4 has become actual again. Workly can't be used in an Electron application.

You need only to replace `iife` with `umd` in [rollup.config.js](https://github.com/pshihn/workly/blob/master/rollup.config.js) in order to resolve it.

**Comment by Finesse** [comment]
There is a temporary workaround for this issue: set the Workly version in your `package.json` to `1.0.1`

**Comment by pshihn** [comment]
My bad. WIll add the UMD build again

**Comment by pshihn** [comment]
(In all honesty I didn't know anyone else was till using this package haha)

**Comment by pshihn** [comment]
Fixed by https://github.com/pshihn/workly/pull/14

**Comment by pshihn** [comment]
v1.3.0 has the UMD build

**Comment by Finesse** [comment]
Thank you
