### ISSUE TITLE
Similar work

### ISSUE THREAD

**Issue by zaygraveyard** [pshihn/workly#3]
Not really an issue but I was wondering if you're aware of @developit's [workerize](https://github.com/developit/workerize) and [greenlet](https://github.com/developit/greenlet) ?

**Comment by pshihn** [comment]
Tes I'm aware of those. We have different approaches to solving the same problem. I wrote this code as part of a separate project, and decided to spin it out as stand alone. 
A couple of things workly is better at is dealing with [classes](https://github.com/pshihn/workly#usage) (exposes all methods in a class including constructor) and code with external dependencies using [custom worker scripts](https://github.com/pshihn/workly#custom-workers).
Workerize is better at dealing with modules and has a slightly smaller footprint.
