### ISSUE TITLE
Support for Transferables?

### ISSUE THREAD

**Issue by bclinkinbeard** [pshihn/workly#6]
Are there plans to add it? Open to PRs? This lib looks awesome but I need Transferable support.

**Comment by pshihn** [comment]
I'm working on that actually. I'd be curious to know more about your use case.
Btw, https://github.com/GoogleChromeLabs/comlink - a similar lib, may already support  your needs.

**Comment by bclinkinbeard** [comment]
Thanks, I am starting to look at comlink as well. The use case is we have large collections/graphs of protocol buffer objects that we need to pass between the main thread and workers.
